### PR TITLE
Update to newest ROS files and add can_msgs

### PR DESCRIPTION
**Pull request by strongly-typed**

### CODE REVIEW

**Comment by salkinium** [comment]
Thanks!

In the long term, I'd like to see this automated somehow in CircleCI, like I did with cmsis-header-stm32 and cmsis-5-partial. The control point is then only about updating the submodule SHA in modm, instead of this two-step approach.

**Comment by strongly-typed** [comment]
Yes, I am working on this. Especially to see when updates are due.

**Comment by salkinium** [comment]
> What CI shall we choose?

Use what is most comfortable for you, as long as I don't have to maintain it 😉.

> `xpcc_ros_lib` must move to to modm (and not be forked from me)

Yes. Unless there is a good reason not to?

> Shall I proceed with the 3rd option?

Yes, you can send me your deploy key via email.

**Comment by strongly-typed** [comment]
## I set up
1. Github repository ros-lib
https://github.com/modm-io/ros-lib
1. Github Deploy Key to push to that repo
https://github.com/modm-io/ros-lib/settings/keys
1. GitLab mirror of Github for CI/CD
https://gitlab.com/modm-io/ros-lib
1. GitLab CI/CD Pipeline
https://gitlab.com/modm-io/ros-lib/pipelines
1. GitLab checked in the code successfully to Gitlab
https://github.com/modm-io/ros-lib/commit/99b827fe7241af5945fe710a7dbc94e31a9999c0
1. GitLab Cron job to regularly rebuild
https://gitlab.com/modm-io/ros-lib/pipeline_schedules
1. Github PR to change modm gitsubmodule
https://github.com/modm-io/modm/pull/90

## What is missing
1. Email notification on updates
Is there anything like this in place for cmsis-header-stm32 and cmsis-5-partial?
1. Automatic test if updates would break modm
1. Automatic PR generation for modm
1. Word domination

**Comment by salkinium** [comment]
> 1. Email notification on updates
> Is there anything like this in place for cmsis-header-stm32 and cmsis-5-partial?

Not for successful updates, only for failing updates via TravisCI.

> 2. Automatic test if updates would break modm
> 3. Automatic PR generation for modm

Yeah, should be solved in modm by upgrading all submodules maybe 2w before the quarterly release.

**Pull request merged**
